mysql:
  image: mysql:5.6.23
  environment:
    - MAGENTO_ADMIN_EMAIL=feifan@me.com
    - MAGENTO_ADMIN_FIRSTNAME=Admin
    - MAGENTO_ADMIN_LASTNAME=MyStore
    - MAGENTO_ADMIN_PASSWORD=magentorocks1
    - MAGENTO_ADMIN_USERNAME=admin
    - MAGENTO_DEFAULT_CURRENCY=USD
    - MAGENTO_LOCALE=en_US
    - MAGENTO_TIMEZONE=America/Los_Angeles
    - MAGENTO_URL=http://192.168.99.100
    - MYSQL_DATABASE=magento
    - MYSQL_HOST=mysql
    - MYSQL_USER=magento
    - MYSQL_PASSWORD=magento
    - MYSQL_ROOT_PASSWORD=H3110_W0R1D!

#phpMyAdmin:
#  image: corbinu/docker-phpmyadmin
#  links:
#    - mysql
#  ports:
#    - 8181:80
#  env_file:
#    - magento/env

magento:
  image: feifanz/dockercomposedemo_magento
  ports:
    - 80:80
  links:
    - mysql
  environment:
    - MAGENTO_ADMIN_EMAIL=feifan@me.com
    - MAGENTO_ADMIN_FIRSTNAME=Admin
    - MAGENTO_ADMIN_LASTNAME=MyStore
    - MAGENTO_ADMIN_PASSWORD=magentorocks1
    - MAGENTO_ADMIN_USERNAME=admin
    - MAGENTO_DEFAULT_CURRENCY=USD
    - MAGENTO_LOCALE=en_US
    - MAGENTO_TIMEZONE=America/Los_Angeles
    - MAGENTO_URL=http://192.168.99.100
    - MYSQL_DATABASE=magento
    - MYSQL_HOST=mysql
    - MYSQL_USER=magento
    - MYSQL_PASSWORD=magento
    - MYSQL_ROOT_PASSWORD=H3110_W0R1D!
